
package kelvinbroekman.messages;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import kelvinbroekman.request.RequestInput;
import kelvinbroekman.response.ResponseOutput;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BerekenStandaardDeviatie", targetNamespace = "http://kelvinBroekman/messages")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    kelvinbroekman.applicatiefout.ObjectFactory.class,
    kelvinbroekman.request.ObjectFactory.class,
    kelvinbroekman.response.ObjectFactory.class
})
public interface BerekenStandaardDeviatie {


    /**
     * 
     * @param request
     * @return
     *     returns kelvinbroekman.response.ResponseOutput
     * @throws Inputfault
     */
    @WebMethod(operationName = "CalculateDeviatie")
    @WebResult(name = "responseOutput", targetNamespace = "http://kelvinBroekman/response", partName = "response")
    public ResponseOutput calculateDeviatie(
        @WebParam(name = "requestInput", targetNamespace = "http://kelvinBroekman/request", partName = "request")
        RequestInput request)
        throws Inputfault
    ;

}
